// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview Suggests similar material items based on existing properties.
 *
 * - suggestSimilarMaterial - A function that suggests similar material items.
 * - SuggestSimilarMaterialInput - The input type for the suggestSimilarMaterial function.
 * - SuggestSimilarMaterialOutput - The return type for the suggestSimilarMaterial function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SuggestSimilarMaterialInputSchema = z.object({
  name: z.string().describe('The name of the material item.'),
  type: z.string().describe('The type of the material item.'),
  code: z.string().describe('The code of the material item.'),
  category: z.string().describe('The category of the material item.'),
  status: z.string().describe('The status of the material item (e.g., healthy, defective).'),
});
export type SuggestSimilarMaterialInput = z.infer<typeof SuggestSimilarMaterialInputSchema>;

const SuggestSimilarMaterialOutputSchema = z.object({
  suggestions: z.array(
    z.object({
      name: z.string().describe('The name of the suggested material item.'),
      type: z.string().describe('The type of the suggested material item.'),
      code: z.string().describe('The code of the suggested material item.'),
      category: z.string().describe('The category of the suggested material item.'),
      status: z.string().describe('The status of the suggested material item.'),
      similarityScore: z.number().describe('A score indicating how similar the item is to the input.'),
    })
  ).describe('A list of similar material items with their properties and similarity scores.'),
});
export type SuggestSimilarMaterialOutput = z.infer<typeof SuggestSimilarMaterialOutputSchema>;

export async function suggestSimilarMaterial(input: SuggestSimilarMaterialInput): Promise<SuggestSimilarMaterialOutput> {
  return suggestSimilarMaterialFlow(input);
}

const suggestSimilarMaterialPrompt = ai.definePrompt({
  name: 'suggestSimilarMaterialPrompt',
  input: {schema: SuggestSimilarMaterialInputSchema},
  output: {schema: SuggestSimilarMaterialOutputSchema},
  prompt: `You are a warehouse inventory management expert. Given the properties of a material item, suggest other similar items that might exist in a warehouse inventory.

Material Item Properties:
Name: {{{name}}}
Type: {{{type}}}
Code: {{{code}}}
Category: {{{category}}}
Status: {{{status}}}

Suggest at least three similar items, including their name, type, code, category, status and also provide a numeric score representing the similarity between the input material and the suggested material. Ensure the suggestions are valid and relevant to warehouse inventory.

Format your output as a JSON array of objects, each object representing a suggested material item, and include a 'similarityScore' (0-1) for each suggested item.`,
});

const suggestSimilarMaterialFlow = ai.defineFlow(
  {
    name: 'suggestSimilarMaterialFlow',
    inputSchema: SuggestSimilarMaterialInputSchema,
    outputSchema: SuggestSimilarMaterialOutputSchema,
  },
  async input => {
    const {output} = await suggestSimilarMaterialPrompt(input);
    return output!;
  }
);
